[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "^17.0.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "^10.0.0"

[[constraint]]
  name = "github.com/gobuffalo/envy"
  version = "1.6.3"

[prune]
  go-tests = true
  unused-packages = true
